In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("IMDb_movies.csv",sep=',')

C:\Users\Salah\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
data.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,...,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,None,Charles Tait,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0

In [4]:
data = data.drop(['usa_gross_income', 'worlwide_gross_income',"metascore" ], axis=1)

In [5]:
columns = data.columns

In [6]:
columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'avg_vote', 'votes',
       'budget', 'reviews_from_users', 'reviews_from_critics'],
      dtype='object')

In [7]:
data = data.rename(columns={"imdb_title_id":"imdb title id", "original_title":"original title", "date_published":"date",
                            "production_company":"producer","avg_vote":"average of votes", "votes":"number of votes",
                            "reviews_from_users":"number of reviews from users","reviews_from_critics":"number of reviews from critics"})

In [8]:
columns = data.columns
columns

Index(['imdb title id', 'title', 'original title', 'year', 'date', 'genre',
       'duration', 'country', 'language', 'director', 'writer', 'producer',
       'actors', 'description', 'average of votes', 'number of votes',
       'budget', 'number of reviews from users',
       'number of reviews from critics'],
      dtype='object')

In [9]:
data.shape

(85855, 19)

In [10]:
data = data.sort_values(by=['average of votes', 'number of votes'], ascending=False)

In [11]:
data.iloc[:5000,:]

,imdb title id,title,original title,year,date,genre,duration,country,language,director,writer,producer,actors,description,average of votes,number of votes,budget,number of reviews from users,number of reviews from critics
83275,tt7822474,Suvarna Sundari,Suvarna Sundari,2019,2019-05-31,"Action, Thriller",120,India,"Telugu, Kannada",Msn Surya,NaN,S Team Pictures,"Shamna Kasim, Sakshi Chaudhary, Jaya Prada, Av...","The movie revolves around an idol, Suvarna Sun...",9.9,896,NaN,NaN,2.0
84995,tt9008642,Notuku Potu,Notuku Potu,2017,2017-03-24,"Horror, Mystery",121,India,Telugu,Basheed S.K.,NaN,SBK Films,"Mumait Khan, Manisha Koirala, Arjun Sarja",Notuku Potu is a crime story laced with elemen...,9.8,926,NaN,2.0,1.0
56032,tt12492650,Ek,Ek,2019,2019-06-14,"Action, Drama",129,India,Telugu,Sampath Rudra,Harik Krishna,K World Movies,"Bishnu Adhikari, Himanshi Khurana, Aparna Shar...",EK is a love story set in the context of ever ...,9.8,527,INR 20000000,NaN,NaN
54217,tt11207902,Lejos de Casa pelicula Venezolana,Lejos de Casa pelicula Venezolana,2020,2020-03-19,"Drama, History",87,Venezuela,Spanish,Abner Official,"Dariana Jozh, Abner Official",NaN,"Angibell, Gabriel Buitrago, Darwing, Dariana J...","Samuel, a young Venezuelan, emigrates from his...",9.8,133,$ 5000,NaN,NaN
55310,tt11976170,Jeeudo,Jeeudo,2020,2020-02-27,"Drama, Romance",150,India,"English, Nepali",Aalmist Subba,"Aalmist Subba, Chanchal Thapa",Aalmist Productions,"Prashant Baraili, Davina, Pranisha Gahatraj, P...","""A TALE OF LOVE, MYTH, AND FATE"" ""JEEUDO"" (mea...",9.8,130,INR 4700000,114.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7525,tt0045659,Mare crudele,The Cruel Sea,1953,1953-10-23,"Drama, War",126,UK,English,Charles Frend,"Nicholas Monsarrat, Eric Ambler",Ealing Studios,"Jack Hawkins, Donald Sinden, John Stratton, De...",The World War II adventures of a British convo...,7.5,3965,NaN,65.0,27.0
22291,tt0090203,In viaggio verso Bountiful,The Trip to Bountiful,1985,1986-01-24,Drama,108,USA,English,Peter Masterson,"Horton Foote, Horton Foote",Bountiful Film Partners,"Geraldine Page, John Heard, Carlin Glynn, Rich...","In 1940s Texas, an elderly woman is determined...",7.5,3956,NaN,72.0,17.0
4208,tt0034946,Delitti senza castigo,Kings Row,1942,1948-10-28,"Drama, Mystery, Romance",127,USA,"English, French",Sam Wood,"Casey Robinson, Henry Bellamann",Warner Bros.,"Ann Sheridan, Robert Cummings, Ronald Reagan, ...",The dark side and hypocrisy of provincial Amer...,7.5,3940,NaN,72.0,19.0
12279,tt0059358,Qualcuno da odiare,King Rat,1965,1965-10-27,"Drama, War",134,USA,"English, Malay, Japanese",Bryan Forbes,"James Clavell, Bryan Forbes",Coleytown,"George Segal, Tom Courtenay, James Fox, Patric...",Fast-talking wheeler-dealer Corporal King is s...,7.5,3929,NaN,49.0,16.0
16568,tt0071585,Gruppo di famiglia in un interno,Gruppo di famiglia in un interno,1974,1975-03-19,"Drama, Romance",126,"Italy, France","Italian, English",Luchino Visconti,"Enrico Medioli, Suso Cecchi D'Amico",Rusconi Film,"Burt Lancaster, Helmut Berger, Silvana Mangano...","A reclusive, retired professor is faced with c...",7.5,3917,NaN,16.0,46.0

In [15]:
data.iloc[5,:]

imdb title id                                                            tt12747588
title                                                                     Meka Suri
original title                                                            Meka Suri
year                                                                           2020
date                                                                     2020-07-31
genre                                                               Crime, Thriller
duration                                                                         86
country                                                                       India
language                                                                     Telugu
director                                                           Trinadh Velisila
writer                                                                          NaN
producer                                                        Simba Entertainment
actors                            Abhinay, Naresh Byreddy, Sharat Kumar, Sravan,...
description                       The story revolves around Meka Suri, a butcher...
average of votes                                                                9.7
number of votes                                                                1126
budget                                                                          NaN
number of reviews from users                                                  502.0
number of reviews from critics                                                  NaN
Name: 56329, dtype: object

In [40]:
mov = {"intents": [
        {"tag": "greeting",
         "patterns": ["Hi", "Hello", "Good morning", "Good evening", "Hey"],
         "responses": ["Hello", "Good to see you", "Hi"],
         "context": [""]
        },
        {"tag": "How are you",
         "patterns": ["How are you?", "How’s it going?", "How’s everything?", "How are things", "What's up", "What’s been going on"],
         "responses": ["I'm fine thank you", "Fine, what about you?", "Good and you?"],
         "context": [""]
        },
        {"tag": "goodbye",
         "patterns": ["See you", "See ya", "Bye", "See you later", "Goodbye", "Nice chatting to you, bye", "Till next time"],
         "responses": ["See you!", "Have a nice day", "Bye! Come back again soon."],
         "context": [""]
        },
        {"tag": "thanks",
         "patterns": ["Thanks", "Thank you", "That's helpful", "Awesome, thanks", "Thanks for helping me"],
         "responses": ["Happy to help!", "Any time!", "My pleasure"],
         "context": [""]
        },
        {"tag": "noanswer",
         "patterns": [],
         "responses": ["Sorry, can't understand you", "Please give me more info", "Not sure I understand"],
         "context": [""]
        },
        {"tag": "service",
         "patterns": ["What can you do?", "What can you provide?", "What's your role?", "What service do you provide?", "What type of information do you give?"],
         "responses": ["I can provide you with information about 85855 movies", "I can give you information about 85855 movies"],
         "context": [""]
        },
        {"tag": "insluts",
         "patterns": ["Fuck you", "Fuck off", "Are you dumb?", "Are you stupid?", "Dumb bot", "Stupid bot"],
         "responses": ["I won't reply to that", "Be polite please", "Watch your language" ,"What???????????"],
         "context": [""]
        }
]}
mov

{'intents': [{'tag': 'greeting',
   'patterns': ['Hi', 'Hello', 'Good morning', 'Good evening', 'Hey'],
   'responses': ['Hello', 'Good to see you', 'Hi'],
   'context': ['']},
  {'tag': 'How are you',
   'patterns': ['How are you?',
    'How’s it going?',
    'How’s everything?',
    'How are things',
    "What's up",
    'What’s been going on'],
   'responses': ["I'm fine thank you",
    'Fine, what about you?',
    'Good and you?'],
   'context': ['']},
  {'tag': 'goodbye',
   'patterns': ['See you',
    'See ya',
    'Bye',
    'See you later',
    'Goodbye',
    'Nice chatting to you, bye',
    'Till next time'],
   'responses': ['See you!', 'Have a nice day', 'Bye! Come back again soon.'],
   'context': ['']},
  {'tag': 'thanks',
   'patterns': ['Thanks',
    'Thank you',
    "That's helpful",
    'Awesome, thanks',
    'Thanks for helping me'],
   'responses': ['Happy to help!', 'Any time!', 'My pleasure'],
   'context': ['']},
  {'tag': 'noanswer',
   'patterns': [],
   'responses': ["Sorry, can't understand you",
    'Please give me more info',
    'Not sure I understand'],
   'context': ['']},
  {'tag': 'service',
   'patterns': ['What can you do?',
    'What can you provide?',
    "What's your role?",
    'What service do you provide?',
    'What type of information do you give?'],
   'responses': ['I can provide you with information about 85855 movies',
    'I can give you information about 85855 movies'],
   'context': ['']},
  {'tag': 'insluts',
   'patterns': ['Fuck you',
    'Fuck off',
    'Are you dumb?',
    'Are you stupid?',
    'Dumb bot',
    'Stupid bot'],
   'responses': ["I won't reply to that",
    'Be polite please',
    'Watch your language',
    'What???????????'],
   'context': ['']}]}

In [12]:
columns

Index(['imdb title id', 'title', 'original title', 'year', 'date', 'genre',
       'duration', 'country', 'language', 'director', 'writer', 'producer',
       'actors', 'description', 'average of votes', 'number of votes',
       'budget', 'number of reviews from users',
       'number of reviews from critics'],
      dtype='object')

In [41]:
data.shape[0]

85855

In [42]:
for i in range(5000):
    for j in range(1,len(columns)):
        if columns[j]=="writer" or columns[j]=="producer" or columns[j]=="director":
            mov["intents"] += [{"tag": str(data.iloc[i,:][1] +" "+ columns[j]),
                            "patterns" : [columns[j]+" of "+data.iloc[i,:][1],"Who is the "+columns[j]+" of "+data.iloc[i,:][1], columns[j]+" of "+data.iloc[i,:][1]+"?"],
                            "responses" : [str(data.iloc[i,:][j])],
                            "context" : [""]
                            }]
        elif columns[j]=="actors":
            mov["intents"] += [{"tag": str(data.iloc[i,:][1] +" "+ columns[j]),
                            "patterns" : [columns[j]+" of "+data.iloc[i,:][1],"Who are the principle "+columns[j]+" of "+data.iloc[i,:][1] , "Who are the "+columns[j]+" of "+data.iloc[i,:][1],"Who are the main "+columns[j]+" of "+data.iloc[i,:][1] , columns[j]+" of "+data.iloc[i,:][1]+"?"],
                            "responses" : [str(data.iloc[i,:][j])],
                            "context" : [""]
                            }]
        else:
            mov["intents"] += [{"tag": str(data.iloc[i,:][1] +" "+ columns[j]),
                            "patterns" : [columns[j]+" of "+data.iloc[i,:][1], "What is the "+columns[j]+" of "+data.iloc[i,:][1], columns[j]+" of "+data.iloc[i,:][1]+"?"],
                            "responses" : [str(data.iloc[i,:][j])],
                            "context" : [""]
                            }]
mov

{'intents': [{'tag': 'greeting',
   'patterns': ['Hi', 'Hello', 'Good morning', 'Good evening', 'Hey'],
   'responses': ['Hello', 'Good to see you', 'Hi'],
   'context': ['']},
  {'tag': 'How are you',
   'patterns': ['How are you?',
    'How’s it going?',
    'How’s everything?',
    'How are things',
    "What's up",
    'What’s been going on'],
   'responses': ["I'm fine thank you",
    'Fine, what about you?',
    'Good and you?'],
   'context': ['']},
  {'tag': 'goodbye',
   'patterns': ['See you',
    'See ya',
    'Bye',
    'See you later',
    'Goodbye',
    'Nice chatting to you, bye',
    'Till next time'],
   'responses': ['See you!', 'Have a nice day', 'Bye! Come back again soon.'],
   'context': ['']},
  {'tag': 'thanks',
   'patterns': ['Thanks',
    'Thank you',
    "That's helpful",
    'Awesome, thanks',
    'Thanks for helping me'],
   'responses': ['Happy to help!', 'Any time!', 'My pleasure'],
   'context': ['']},
  {'tag': 'noanswer',
   'patterns': [],
   'responses': ["Sorry, can't understand you",
    'Please give me more info',
    'Not sure I understand'],
   'context': ['']},
  {'tag': 'service',
   'patterns': ['What can you do?',
    'What can you provide?',
    "What's your role?",
    'What service do you provide?',
    'What type of information do you give?'],
   'responses': ['I can provide you with information about 85855 movies',
    'I can give you information about 85855 movies'],
   'context': ['']},
  {'tag': 'insluts',
   'patterns': ['Fuck you',
    'Fuck off',
    'Are you dumb?',
    'Are you stupid?',
    'Dumb bot',
    'Stupid bot'],
   'responses': ["I won't reply to that",
    'Be polite please',
    'Watch your language',
    'What???????????'],
   'context': ['']},
  {'tag': 'Suvarna Sundari title',
   'patterns': ['title of Suvarna Sundari',
    'What is the title of Suvarna Sundari',
    'title of Suvarna Sundari?'],
   'responses': ['Suvarna Sundari'],
   'context': ['']},
  {'tag': 'Suvarna Sundari original title',
   'patterns': ['original title of Suvarna Sundari',
    'What is the original title of Suvarna Sundari',
    'original title of Suvarna Sundari?'],
   'responses': ['Suvarna Sundari'],
   'context': ['']},
  {'tag': 'Suvarna Sundari year',
   'patterns': ['year of Suvarna Sundari',
    'What is the year of Suvarna Sundari',
    'year of Suvarna Sundari?'],
   'responses': ['2019'],
   'context': ['']},
  {'tag': 'Suvarna Sundari date',
   'patterns': ['date of Suvarna Sundari',
    'What is the date of Suvarna Sundari',
    'date of Suvarna Sundari?'],
   'responses': ['2019-05-31'],
   'context': ['']},
  {'tag': 'Suvarna Sundari genre',
   'patterns': ['genre of Suvarna Sundari',
    'What is the genre of Suvarna Sundari',
    'genre of Suvarna Sundari?'],
   'responses': ['Action, Thriller'],
   'context': ['']},
  {'tag': 'Suvarna Sundari duration',
   'patterns': ['duration of Suvarna Sundari',
    'What is the duration of Suvarna Sundari',
    'duration of Suvarna Sundari?'],
   'responses': ['120'],
   'context': ['']},
  {'tag': 'Suvarna Sundari country',
   'patterns': ['country of Suvarna Sundari',
    'What is the country of Suvarna Sundari',
    'country of Suvarna Sundari?'],
   'responses': ['India'],
   'context': ['']},
  {'tag': 'Suvarna Sundari language',
   'patterns': ['language of Suvarna Sundari',
    'What is the language of Suvarna Sundari',
    'language of Suvarna Sundari?'],
   'responses': ['Telugu, Kannada'],
   'context': ['']},
  {'tag': 'Suvarna Sundari director',
   'patterns': ['director of Suvarna Sundari',
    'Who is the director of Suvarna Sundari',
    'director of Suvarna Sundari?'],
   'responses': ['Msn Surya'],
   'context': ['']},
  {'tag': 'Suvarna Sundari writer',
   'patterns': ['writer of Suvarna Sundari',
    'Who is the writer of Suvarna Sundari',
    'writer of Suvarna Sundari?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Suvarna Sundari producer',
   'patterns': ['producer of Suvarna Sundari',
    'Who is the producer of Suvarna Sundari',
    'producer of Suvarna Sundari?'],
   'responses': ['S Team Pictures'],
   'context': ['']},
  {'tag': 'Suvarna Sundari actors',
   'patterns': ['actors of Suvarna Sundari',
    'Who are the principle actors of Suvarna Sundari',
    'Who are the actors of Suvarna Sundari',
    'Who are the main actors of Suvarna Sundari',
    'actors of Suvarna Sundari?'],
   'responses': ['Shamna Kasim, Sakshi Chaudhary, Jaya Prada, Avantika Vandanapu, Avinash, Indra, Srinivasa Rao Kota, Sai Kumar, Nagineedu, Sathya Prakash, Raam'],
   'context': ['']},
  {'tag': 'Suvarna Sundari description',
   'patterns': ['description of Suvarna Sundari',
    'What is the description of Suvarna Sundari',
    'description of Suvarna Sundari?'],
   'responses': ['The movie revolves around an idol, Suvarna Sundari and the effects of it. The idol, also known as Trinetri, dates back to 15th century. Whoever possesses the idol, becomes a victim of ...'],
   'context': ['']},
  {'tag': 'Suvarna Sundari average of votes',
   'patterns': ['average of votes of Suvarna Sundari',
    'What is the average of votes of Suvarna Sundari',
    'average of votes of Suvarna Sundari?'],
   'responses': ['9.9'],
   'context': ['']},
  {'tag': 'Suvarna Sundari number of votes',
   'patterns': ['number of votes of Suvarna Sundari',
    'What is the number of votes of Suvarna Sundari',
    'number of votes of Suvarna Sundari?'],
   'responses': ['896'],
   'context': ['']},
  {'tag': 'Suvarna Sundari budget',
   'patterns': ['budget of Suvarna Sundari',
    'What is the budget of Suvarna Sundari',
    'budget of Suvarna Sundari?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Suvarna Sundari number of reviews from users',
   'patterns': ['number of reviews from users of Suvarna Sundari',
    'What is the number of reviews from users of Suvarna Sundari',
    'number of reviews from users of Suvarna Sundari?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Suvarna Sundari number of reviews from critics',
   'patterns': ['number of reviews from critics of Suvarna Sundari',
    'What is the number of reviews from critics of Suvarna Sundari',
    'number of reviews from critics of Suvarna Sundari?'],
   'responses': ['2.0'],
   'context': ['']},
  {'tag': 'Notuku Potu title',
   'patterns': ['title of Notuku Potu',
    'What is the title of Notuku Potu',
    'title of Notuku Potu?'],
   'responses': ['Notuku Potu'],
   'context': ['']},
  {'tag': 'Notuku Potu original title',
   'patterns': ['original title of Notuku Potu',
    'What is the original title of Notuku Potu',
    'original title of Notuku Potu?'],
   'responses': ['Notuku Potu'],
   'context': ['']},
  {'tag': 'Notuku Potu year',
   'patterns': ['year of Notuku Potu',
    'What is the year of Notuku Potu',
    'year of Notuku Potu?'],
   'responses': ['2017'],
   'context': ['']},
  {'tag': 'Notuku Potu date',
   'patterns': ['date of Notuku Potu',
    'What is the date of Notuku Potu',
    'date of Notuku Potu?'],
   'responses': ['2017-03-24'],
   'context': ['']},
  {'tag': 'Notuku Potu genre',
   'patterns': ['genre of Notuku Potu',
    'What is the genre of Notuku Potu',
    'genre of Notuku Potu?'],
   'responses': ['Horror, Mystery'],
   'context': ['']},
  {'tag': 'Notuku Potu duration',
   'patterns': ['duration of Notuku Potu',
    'What is the duration of Notuku Potu',
    'duration of Notuku Potu?'],
   'responses': ['121'],
   'context': ['']},
  {'tag': 'Notuku Potu country',
   'patterns': ['country of Notuku Potu',
    'What is the country of Notuku Potu',
    'country of Notuku Potu?'],
   'responses': ['India'],
   'context': ['']},
  {'tag': 'Notuku Potu language',
   'patterns': ['language of Notuku Potu',
    'What is the language of Notuku Potu',
    'language of Notuku Potu?'],
   'responses': ['Telugu'],
   'context': ['']},
  {'tag': 'Notuku Potu director',
   'patterns': ['director of Notuku Potu',
    'Who is the director of Notuku Potu',
    'director of Notuku Potu?'],
   'responses': ['Basheed S.K.'],
   'context': ['']},
  {'tag': 'Notuku Potu writer',
   'patterns': ['writer of Notuku Potu',
    'Who is the writer of Notuku Potu',
    'writer of Notuku Potu?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Notuku Potu producer',
   'patterns': ['producer of Notuku Potu',
    'Who is the producer of Notuku Potu',
    'producer of Notuku Potu?'],
   'responses': ['SBK Films'],
   'context': ['']},
  {'tag': 'Notuku Potu actors',
   'patterns': ['actors of Notuku Potu',
    'Who are the principle actors of Notuku Potu',
    'Who are the actors of Notuku Potu',
    'Who are the main actors of Notuku Potu',
    'actors of Notuku Potu?'],
   'responses': ['Mumait Khan, Manisha Koirala, Arjun Sarja'],
   'context': ['']},
  {'tag': 'Notuku Potu description',
   'patterns': ['description of Notuku Potu',
    'What is the description of Notuku Potu',
    'description of Notuku Potu?'],
   'responses': ['Notuku Potu is a crime story laced with elements of horror and thrill. The story is about a man who, after the death of a woman, is pulled into a world of mystery and conspiracy.'],
   'context': ['']},
  {'tag': 'Notuku Potu average of votes',
   'patterns': ['average of votes of Notuku Potu',
    'What is the average of votes of Notuku Potu',
    'average of votes of Notuku Potu?'],
   'responses': ['9.8'],
   'context': ['']},
  {'tag': 'Notuku Potu number of votes',
   'patterns': ['number of votes of Notuku Potu',
    'What is the number of votes of Notuku Potu',
    'number of votes of Notuku Potu?'],
   'responses': ['926'],
   'context': ['']},
  {'tag': 'Notuku Potu budget',
   'patterns': ['budget of Notuku Potu',
    'What is the budget of Notuku Potu',
    'budget of Notuku Potu?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Notuku Potu number of reviews from users',
   'patterns': ['number of reviews from users of Notuku Potu',
    'What is the number of reviews from users of Notuku Potu',
    'number of reviews from users of Notuku Potu?'],
   'responses': ['2.0'],
   'context': ['']},
  {'tag': 'Notuku Potu number of reviews from critics',
   'patterns': ['number of reviews from critics of Notuku Potu',
    'What is the number of reviews from critics of Notuku Potu',
    'number of reviews from critics of Notuku Potu?'],
   'responses': ['1.0'],
   'context': ['']},
  {'tag': 'Ek title',
   'patterns': ['title of Ek', 'What is the title of Ek', 'title of Ek?'],
   'responses': ['Ek'],
   'context': ['']},
  {'tag': 'Ek original title',
   'patterns': ['original title of Ek',
    'What is the original title of Ek',
    'original title of Ek?'],
   'responses': ['Ek'],
   'context': ['']},
  {'tag': 'Ek year',
   'patterns': ['year of Ek', 'What is the year of Ek', 'year of Ek?'],
   'responses': ['2019'],
   'context': ['']},
  {'tag': 'Ek date',
   'patterns': ['date of Ek', 'What is the date of Ek', 'date of Ek?'],
   'responses': ['2019-06-14'],
   'context': ['']},
  {'tag': 'Ek genre',
   'patterns': ['genre of Ek', 'What is the genre of Ek', 'genre of Ek?'],
   'responses': ['Action, Drama'],
   'context': ['']},
  {'tag': 'Ek duration',
   'patterns': ['duration of Ek',
    'What is the duration of Ek',
    'duration of Ek?'],
   'responses': ['129'],
   'context': ['']},
  {'tag': 'Ek country',
   'patterns': ['country of Ek',
    'What is the country of Ek',
    'country of Ek?'],
   'responses': ['India'],
   'context': ['']},
  {'tag': 'Ek language',
   'patterns': ['language of Ek',
    'What is the language of Ek',
    'language of Ek?'],
   'responses': ['Telugu'],
   'context': ['']},
  {'tag': 'Ek director',
   'patterns': ['director of Ek',
    'Who is the director of Ek',
    'director of Ek?'],
   'responses': ['Sampath Rudra'],
   'context': ['']},
  {'tag': 'Ek writer',
   'patterns': ['writer of Ek', 'Who is the writer of Ek', 'writer of Ek?'],
   'responses': ['Harik Krishna'],
   'context': ['']},
  {'tag': 'Ek producer',
   'patterns': ['producer of Ek',
    'Who is the producer of Ek',
    'producer of Ek?'],
   'responses': ['K World Movies'],
   'context': ['']},
  {'tag': 'Ek actors',
   'patterns': ['actors of Ek',
    'Who are the principle actors of Ek',
    'Who are the actors of Ek',
    'Who are the main actors of Ek',
    'actors of Ek?'],
   'responses': ['Bishnu Adhikari, Himanshi Khurana, Aparna Sharma, Prudhviraj, Banerjee, Suman, Sravan'],
   'context': ['']},
  {'tag': 'Ek description',
   'patterns': ['description of Ek',
    'What is the description of Ek',
    'description of Ek?'],
   'responses': ["EK is a love story set in the context of ever growing threat of suicide bombings in the country and across the world. It's a stylishly shot emotional action thriller with realistic ..."],
   'context': ['']},
  {'tag': 'Ek average of votes',
   'patterns': ['average of votes of Ek',
    'What is the average of votes of Ek',
    'average of votes of Ek?'],
   'responses': ['9.8'],
   'context': ['']},
  {'tag': 'Ek number of votes',
   'patterns': ['number of votes of Ek',
    'What is the number of votes of Ek',
    'number of votes of Ek?'],
   'responses': ['527'],
   'context': ['']},
  {'tag': 'Ek budget',
   'patterns': ['budget of Ek', 'What is the budget of Ek', 'budget of Ek?'],
   'responses': ['INR 20000000'],
   'context': ['']},
  {'tag': 'Ek number of reviews from users',
   'patterns': ['number of reviews from users of Ek',
    'What is the number of reviews from users of Ek',
    'number of reviews from users of Ek?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Ek number of reviews from critics',
   'patterns': ['number of reviews from critics of Ek',
    'What is the number of reviews from critics of Ek',
    'number of reviews from critics of Ek?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana title',
   'patterns': ['title of Lejos de Casa pelicula Venezolana',
    'What is the title of Lejos de Casa pelicula Venezolana',
    'title of Lejos de Casa pelicula Venezolana?'],
   'responses': ['Lejos de Casa pelicula Venezolana'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana original title',
   'patterns': ['original title of Lejos de Casa pelicula Venezolana',
    'What is the original title of Lejos de Casa pelicula Venezolana',
    'original title of Lejos de Casa pelicula Venezolana?'],
   'responses': ['Lejos de Casa pelicula Venezolana'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana year',
   'patterns': ['year of Lejos de Casa pelicula Venezolana',
    'What is the year of Lejos de Casa pelicula Venezolana',
    'year of Lejos de Casa pelicula Venezolana?'],
   'responses': ['2020'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana date',
   'patterns': ['date of Lejos de Casa pelicula Venezolana',
    'What is the date of Lejos de Casa pelicula Venezolana',
    'date of Lejos de Casa pelicula Venezolana?'],
   'responses': ['2020-03-19'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana genre',
   'patterns': ['genre of Lejos de Casa pelicula Venezolana',
    'What is the genre of Lejos de Casa pelicula Venezolana',
    'genre of Lejos de Casa pelicula Venezolana?'],
   'responses': ['Drama, History'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana duration',
   'patterns': ['duration of Lejos de Casa pelicula Venezolana',
    'What is the duration of Lejos de Casa pelicula Venezolana',
    'duration of Lejos de Casa pelicula Venezolana?'],
   'responses': ['87'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana country',
   'patterns': ['country of Lejos de Casa pelicula Venezolana',
    'What is the country of Lejos de Casa pelicula Venezolana',
    'country of Lejos de Casa pelicula Venezolana?'],
   'responses': ['Venezuela'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana language',
   'patterns': ['language of Lejos de Casa pelicula Venezolana',
    'What is the language of Lejos de Casa pelicula Venezolana',
    'language of Lejos de Casa pelicula Venezolana?'],
   'responses': ['Spanish'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana director',
   'patterns': ['director of Lejos de Casa pelicula Venezolana',
    'Who is the director of Lejos de Casa pelicula Venezolana',
    'director of Lejos de Casa pelicula Venezolana?'],
   'responses': ['Abner Official'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana writer',
   'patterns': ['writer of Lejos de Casa pelicula Venezolana',
    'Who is the writer of Lejos de Casa pelicula Venezolana',
    'writer of Lejos de Casa pelicula Venezolana?'],
   'responses': ['Dariana Jozh, Abner Official'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana producer',
   'patterns': ['producer of Lejos de Casa pelicula Venezolana',
    'Who is the producer of Lejos de Casa pelicula Venezolana',
    'producer of Lejos de Casa pelicula Venezolana?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana actors',
   'patterns': ['actors of Lejos de Casa pelicula Venezolana',
    'Who are the principle actors of Lejos de Casa pelicula Venezolana',
    'Who are the actors of Lejos de Casa pelicula Venezolana',
    'Who are the main actors of Lejos de Casa pelicula Venezolana',
    'actors of Lejos de Casa pelicula Venezolana?'],
   'responses': ['Angibell, Gabriel Buitrago, Darwing, Dariana Jozh, Marko, Abner Official, Yroski'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana description',
   'patterns': ['description of Lejos de Casa pelicula Venezolana',
    'What is the description of Lejos de Casa pelicula Venezolana',
    'description of Lejos de Casa pelicula Venezolana?'],
   'responses': ['Samuel, a young Venezuelan, emigrates from his country in search of a better life and to help his family, without knowing the difficult situations that he will face as an immigrant.'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana average of votes',
   'patterns': ['average of votes of Lejos de Casa pelicula Venezolana',
    'What is the average of votes of Lejos de Casa pelicula Venezolana',
    'average of votes of Lejos de Casa pelicula Venezolana?'],
   'responses': ['9.8'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana number of votes',
   'patterns': ['number of votes of Lejos de Casa pelicula Venezolana',
    'What is the number of votes of Lejos de Casa pelicula Venezolana',
    'number of votes of Lejos de Casa pelicula Venezolana?'],
   'responses': ['133'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana budget',
   'patterns': ['budget of Lejos de Casa pelicula Venezolana',
    'What is the budget of Lejos de Casa pelicula Venezolana',
    'budget of Lejos de Casa pelicula Venezolana?'],
   'responses': ['$ 5000'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana number of reviews from users',
   'patterns': ['number of reviews from users of Lejos de Casa pelicula Venezolana',
    'What is the number of reviews from users of Lejos de Casa pelicula Venezolana',
    'number of reviews from users of Lejos de Casa pelicula Venezolana?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Lejos de Casa pelicula Venezolana number of reviews from critics',
   'patterns': ['number of reviews from critics of Lejos de Casa pelicula Venezolana',
    'What is the number of reviews from critics of Lejos de Casa pelicula Venezolana',
    'number of reviews from critics of Lejos de Casa pelicula Venezolana?'],
   'responses': ['nan'],
   'context': ['']},
  {'tag': 'Jeeudo title',
   'patterns': ['title of Jeeudo',
    'What is the title of Jeeudo',
    'title of Jeeudo?'],
   'responses': ['Jeeudo'],
   'context': ['']},
  {'tag': 'Jeeudo original title',

In [43]:
import json
with open("movies_imdb.json", "w") as write_file:
    json.dump(mov, write_file)